"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z*^p&7s6l=2^!z%w0^z*^p&7s6l=2^!z%w0^' # Replace with actual secret key in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # In production, set this to your domain, e.g., ['yourdomain.com', 'www.yourdomain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local Apps
    'bookshelf.apps.BookshelfConfig',
    'accounts.apps.AccountsConfig',
]

MIDDLEWARE = [
    # CRITICAL: This middleware enables many of the security settings defined below (HSTS, SSL redirect, etc.).
    # It must be placed near the top.
    'django.middleware.security.SecurityMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Added project-level templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication URLs
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# ===============================================
# CRITICAL SECURITY CONFIGURATIONS (HTTPS & Headers)
# ===============================================

# 1. Enforcing HTTPS Redirects (Step 1)
# Redirects all non-HTTPS requests to HTTPS. Only set to True after SSL/TLS 
# is configured on the web server (e.g., Nginx/Apache).
SECURE_SSL_REDIRECT = True 

# 2. HTTP Strict Transport Security (HSTS) (Step 1)
# Instructs browsers to only access the site using HTTPS for the next year (31,536,000 seconds).
# NOTE: Set this to a non-zero value only when you are certain your site will 
# serve via HTTPS indefinitely, as it is difficult to reverse.
SECURE_HSTS_SECONDS = 31536000 # 1 year

# Includes all subdomains in the HSTS policy.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Allows the site to be submitted to browser HSTS preload lists.
SECURE_HSTS_PRELOAD = True

# 3. Secure Cookies (Step 2)
# Ensures that session cookies are only transmitted over HTTPS.
SESSION_COOKIE_SECURE = True

# Ensures that CSRF cookies are only transmitted over HTTPS.
CSRF_COOKIE_SECURE = True

# 4. Security Headers (Step 3)
# Denies all framing of the site ('DENY') to protect against Clickjacking attacks.
# This setting is processed by the XFrameOptionsMiddleware.
X_FRAME_OPTIONS = 'DENY' 

# Prevents browsers from MIME-sniffing content types (X-Content-Type-Options: nosniff).
# This reduces the risk of XSS attacks.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables the browser's deprecated XSS filtering (X-XSS-Protection: 1; mode=block).
# Useful for compatibility with older browsers.
SECURE_BROWSER_XSS_FILTER = True 

# Optional: Configuration for running behind a reverse proxy (like Nginx)
# If your reverse proxy adds X-Forwarded-Proto, uncomment the following:
# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
AUTH_USER_MODEL = 'bookshelf.CustomUser'