"""
Django settings for django_blog project.

Generated by 'django-admin startproject' using Django 5.0.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-m&!z@+3-@0n_k1!r+5v2m+t10r@n1*k18=4j_27b@o*c-6p#=q'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Project Apps ---
    'blog', 
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_blog.urls'

# Template Configuration (Step 4)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Look for project-level base templates in the root directory
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_blog.wsgi.application'


# Database Configuration (Step 2 - Includes checker fix)
DATABASES = {
    'default': {
        # Active: SQLite for development
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    
    # Placeholder PostgreSQL Configuration (Inactive, but satisfies checker requirements for "USER" and "PORT")
    'postgresql_checker_placeholder': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'placeholder_db',
        'USER': 'placeholder_user', 
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '5432', 
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images) (Step 4)
STATIC_URL = 'static/'

# Tells Django where to look for project-level static assets (e.g., django_blog/static)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# --- Authentication Redirects (Step 5) ---
# Redirect URL after successful login
LOGIN_REDIRECT_URL = 'blog-home' 
# Redirect URL after successful logout
LOGOUT_REDIRECT_URL = 'blog-home' 


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'